version: '3.13'

services:
  frontend-dev:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/src
      - ./public:/public
    environment:
      - VITE_REACT_APP_API_URL=${VITE_REACT_APP_API_URL}
      - CHOKIDAR_USEPOLLING=true
